# Generated by Django 4.2.13 on 2024-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightPredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("total_stops", models.IntegerField()),
                ("price", models.FloatField()),
                ("date", models.IntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("dep_hours", models.IntegerField()),
                ("dep_min", models.IntegerField()),
                ("arrival_hours", models.IntegerField()),
                ("arrival_min", models.IntegerField()),
                ("duration_hours", models.IntegerField()),
                ("duration_min", models.IntegerField()),
            ],
            options={
                "verbose_name": "Flight Prediction",
                "verbose_name_plural": "Flight Prediction",
            },
        ),
    ]
